version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: scheduleflow-db
    environment:
      POSTGRES_DB: scheduleflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nunuhara@11
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: scheduleflow-backend
    depends_on:
      - db
    networks:
      default:
        aliases:
          - backend.railway.internal
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/scheduleflow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: nunuhara@11
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: scheduleflow-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
