// src/pages/MyTimetablesPage.jsx
import React, { useState, useEffect, useCallback } from 'react';
import { getAllTimetables, getActiveTimetable, getTimetableById, getLecturesByTimetableId, lecturesToTimetableGrid } from '../api/eventApi.js';
import ResultPage from './ResultPage.jsx';
import styles from './MyTimetablesPage.module.css';

export default function MyTimetablesPage({ token, onBack, onNewTimetable }) {
  const [timetables, setTimetables] = useState([]);
  const [activeTt, setActiveTt]     = useState(null);
  const [loading, setLoading]       = useState(true);
  const [error, setError]           = useState(null);
  const [selectedResult, setSelectedResult] = useState(null);
  const [viewingDetailId, setViewingDetailId] = useState(null);

  const loadTimetables = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const [allList, currentActive] = await Promise.all([
        getAllTimetables(token).catch(() => []),
        getActiveTimetable(token).catch(() => null)
      ]);
      setTimetables(Array.isArray(allList) ? allList : []);
      setActiveTt(currentActive);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }, [token]);

  useEffect(() => { loadTimetables(); }, [loadTimetables]);

  async function handleViewDetails(ttId) {
    setLoading(true);
    try {
      const [meta, lectures] = await Promise.all([
        getTimetableById(ttId, token).catch(() => ({ id: ttId })),
        getLecturesByTimetableId(ttId, token).catch(() => [])
      ]);
      const { timetable, sectionsList } = lecturesToTimetableGrid(lectures);
      setSelectedResult({
        timetableId: ttId,
        timetable,
        sectionsList,
        meta
      });
      setViewingDetailId(ttId);
    } catch (err) {
      alert('Error fetching timetable details: ' + err.message);
    } finally {
      setLoading(false);
    }
  }

  if (selectedResult) {
    return (
      <ResultPage
        sections={selectedResult.sectionsList || []}
        daysPerWeek={5}
        periodsPerDay={6}
        result={selectedResult}
        onPrev={() => { setSelectedResult(null); setViewingDetailId(null); }}
        onViewMyTimetables={() => { setSelectedResult(null); setViewingDetailId(null); }}
      />
    );
  }

  return (
    <div className={styles.root}>
      {/* Top Header */}
      <div className={styles.topbar}>
        <button className={styles.back_btn} onClick={onBack}>← Dashboard</button>
        <div>
          <h1 className={styles.title}>📋 My Timetables</h1>
          <p className={styles.subtitle}>View and manage all generated timetables and historical versions</p>
        </div>
        <button className={styles.primary_btn} onClick={onNewTimetable}>+ New Timetable</button>
      </div>

      {loading && <div className={styles.loading_box}>Loading timetables…</div>}
      {error && <div className={styles.error_box}>⚠ {error}</div>}

      {/* Active Timetable Banner */}
      {activeTt && !loading && (
        <div className={styles.active_card}>
          <div className={styles.active_badge}>ACTIVE TIMETABLE</div>
          <h3>{activeTt.name || `Timetable #${activeTt.id}`}</h3>
          <p>Semester: <strong>{activeTt.semester || 'N/A'}</strong> | Year: <strong>{activeTt.academicYear || 'N/A'}</strong> | Generated By: <strong>{activeTt.generatedBy || 'Admin'}</strong></p>
          <button className={styles.primary_btn} onClick={() => handleViewDetails(activeTt.id)}>
            View Active Timetable →
          </button>
        </div>
      )}

      {/* All Timetables Grid */}
      {!loading && (
        <div className={styles.section}>
          <h3 className={styles.section_title}>All Timetable Versions ({timetables.length})</h3>
          {timetables.length === 0 ? (
            <div className={styles.empty_box}>
              <p>No timetables generated yet.</p>
              <button className={styles.primary_btn} onClick={onNewTimetable}>Generate First Timetable</button>
            </div>
          ) : (
            <div className={styles.grid}>
              {timetables.map(tt => (
                <div key={tt.id} className={`${styles.card} ${tt.status === 'ACTIVE' ? styles.card_active : ''}`}>
                  <div className={styles.card_header}>
                    <span className={styles.tt_id}>#{tt.id}</span>
                    <span className={`${styles.status_badge} ${tt.status === 'ACTIVE' ? styles.badge_active : styles.badge_archived}`}>
                      {tt.status || 'ARCHIVED'}
                    </span>
                  </div>
                  <h4 className={styles.tt_title}>{tt.name || `Timetable #${tt.id}`}</h4>
                  <div className={styles.tt_meta}>
                    <div>🎓 Semester: <strong>{tt.semester || 'N/A'}</strong></div>
                    <div>📅 Academic Year: <strong>{tt.academicYear || 'N/A'}</strong></div>
                    <div>👤 Generated By: <strong>{tt.generatedBy || 'Admin'}</strong></div>
                    <div>🕐 Created: <strong>{tt.createdAt ? new Date(tt.createdAt).toLocaleString() : 'N/A'}</strong></div>
                  </div>
                  <button className={styles.view_btn} onClick={() => handleViewDetails(tt.id)}>
                    View Details →
                  </button>
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
